# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68b406aa6c3dc505a58959a5297d4606199055ded5385da10405cd10cd419f8ef913b170776445cb5124cc30fdb9b57337a4c66974ce9977ebd0a43fe31dd1b

test:
  secret_key_base: e34f6756b9e173453da71a8cb7ed394f666ba63b080b5f11b99ffa1e9dcdb8caaf410a5639d02e8332c51ada51c04cc9b3f6049adbfcf1b619f5bd7a6c687ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
